module.exports = {
    "pages": [
        {
            "id": 10870,
            "path": "/index",
            "name": "首页",
            "templates": [
                10844
            ],
            "interfaces": [
                14097
            ],
            "description": "",
            "parameters": [
                {
                    "id": 17007,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "province",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "省",
                    "updateTime": 1454307211000,
                    "defaultValue": "浙江"
                },
                {
                    "id": 17008,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "city",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "市",
                    "updateTime": 1454307211000,
                    "defaultValue": "杭州"
                },
                {
                    "id": 17996,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "isChinese",
                    "originalType": 10003,
                    "type": 10003,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "是否中国人",
                    "updateTime": 1454307211000,
                    "defaultValue": "true"
                }
            ],
            "updateTime": 1454307221000
        }
    ],
    "interfaces": [
        {
            "id": 14103,
            "name": "AddAddressInfoCase3",
            "className": "",
            "description": "添加一个地址，测试输入参数形式一",
            "path": "/address/add",
            "method": 1,
            "isRest": 1,
            "inputs": [
                {
                    "id": 17007,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "province",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "省",
                    "createTime": 1449458824000,
                    "updateTime": 1449458824000,
                    "defaultValue": "浙江"
                },
                {
                    "id": 17008,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "city",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "市",
                    "createTime": 1449458824000,
                    "updateTime": 1449458824000,
                    "defaultValue": "杭州"
                },
                {
                    "id": 17996,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "isChinese",
                    "originalType": 10003,
                    "type": 10003,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "是否中国人",
                    "createTime": 1449458824000,
                    "updateTime": 1449458824000,
                    "defaultValue": "true"
                }
            ],
            "outputs": [],
            "headers": [],
            "updateTime": 1449469886000
        },
        {
            "id": 14104,
            "name": "AddAddressInfoCase2",
            "className": "",
            "description": "添加一个地址，测试输入参数形式2",
            "path": "/address/add",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28360,
                    "name": "address",
                    "type": 11256,
                    "isPrimite": 0,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449458883000,
                    "updateTime": 1449458883000,
                    "defaultValue": ""
                }
            ],
            "outputs": [],
            "headers": [],
            "updateTime": 1449458923000
        },
        {
            "id": 14117,
            "name": "AddAddressInfoCase1",
            "className": "AddAddressInfo",
            "description": "",
            "path": "/address/add/case1",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28388,
                    "name": "province",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "省省",
                    "createTime": 1449469821000,
                    "updateTime": 1450179729000,
                    "defaultValue": ""
                },
                {
                    "id": 28389,
                    "name": "city",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "市",
                    "createTime": 1449469821000,
                    "updateTime": 1449750211000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 17213,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449469821000,
                    "updateTime": 1449469821000,
                    "defaultValue": ""
                },
                {
                    "id": 17214,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "message",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449469821000,
                    "updateTime": 1449469821000,
                    "defaultValue": ""
                },
                {
                    "id": 17215,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "testResult",
                    "originalType": 10000,
                    "type": 11293,
                    "typeName": "ProductInfo",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449469821000,
                    "updateTime": 1449469821000,
                    "defaultValue": ""
                }
            ],
            "headers": [
                {
                    "id": 28873,
                    "name": "Content-Type",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "内容长度",
                    "createTime": 1450232891000,
                    "updateTime": 1450233904000,
                    "defaultValue": "application/json"
                },
                {
                    "id": 28875,
                    "name": "Transfer-Encoding",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "传输编码",
                    "createTime": 1450233234000,
                    "updateTime": 1450233234000,
                    "defaultValue": ""
                },
                {
                    "id": 28876,
                    "name": "Content-Encoding",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "内容编码",
                    "createTime": 1450234709000,
                    "updateTime": 1450236611000,
                    "defaultValue": "gzip"
                },
                {
                    "id": 28926,
                    "name": "Cookie",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1450253521000,
                    "updateTime": 1450253521000,
                    "defaultValue": ""
                }
            ],
            "updateTime": 1450253521000
        },
        {
            "id": 14105,
            "name": "GetAddressInfoCase2",
            "className": "",
            "description": "对应输出参数Case2",
            "path": "/address/get",
            "method": 1,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28361,
                    "name": "name",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459019000,
                    "updateTime": 1449459019000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 17007,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "province",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "省",
                    "createTime": 1449459019000,
                    "updateTime": 1449459019000,
                    "defaultValue": "浙江"
                },
                {
                    "id": 17008,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "city",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "市",
                    "createTime": 1449459019000,
                    "updateTime": 1449459019000,
                    "defaultValue": "杭州"
                },
                {
                    "id": 17996,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "isChinese",
                    "originalType": 10003,
                    "type": 10003,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "是否中国人",
                    "createTime": 1449459019000,
                    "updateTime": 1449459019000,
                    "defaultValue": "true"
                }
            ],
            "headers": [],
            "updateTime": 1449459083000
        },
        {
            "id": 14111,
            "name": "GetAddressInfoCase3",
            "className": "",
            "description": "",
            "path": "/address/get/case3",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 17213,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459643000,
                    "updateTime": 1449459643000,
                    "defaultValue": ""
                },
                {
                    "id": 17214,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "message",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459643000,
                    "updateTime": 1449459643000,
                    "defaultValue": ""
                },
                {
                    "id": 17215,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "testResult",
                    "originalType": 10000,
                    "type": 11256,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459643000,
                    "updateTime": 1449459643000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449459643000
        },
        {
            "id": 14106,
            "name": "GetAddressInfoCase4",
            "className": "",
            "description": "测试输出参数，对应Case 4.",
            "path": "/address/get/case4",
            "method": 1,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28362,
                    "name": "code",
                    "type": 10002,
                    "isPrimite": 0,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459187000,
                    "updateTime": 1449459187000,
                    "defaultValue": ""
                },
                {
                    "id": 28363,
                    "name": "message",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459187000,
                    "updateTime": 1449459187000,
                    "defaultValue": ""
                },
                {
                    "id": 28364,
                    "name": "address",
                    "type": 11256,
                    "isPrimite": 0,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459187000,
                    "updateTime": 1449459187000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449459187000
        },
        {
            "id": 14107,
            "name": "GetAddressInfoCase5",
            "className": "",
            "description": "",
            "path": "/address/get/case5",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28365,
                    "name": "city",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459367000,
                    "updateTime": 1449459367000,
                    "defaultValue": ""
                },
                {
                    "id": 28366,
                    "name": "province",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459367000,
                    "updateTime": 1449459367000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449459367000
        },
        {
            "id": 14108,
            "name": "GetAddressInfoCase6",
            "className": "",
            "description": "",
            "path": "/address/get/case6",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28367,
                    "name": "address",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459419000,
                    "updateTime": 1449459419000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449459419000
        },
        {
            "id": 14102,
            "name": "GetShipAddressList",
            "className": "",
            "description": "获取地址信息，测试输出参数Case1",
            "path": "/address/list.json",
            "method": 1,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28359,
                    "name": "data",
                    "type": 11306,
                    "isPrimite": 0,
                    "typeName": "TestShipAddress",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "createTime": 1449458567000,
                    "updateTime": 1449458567000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449458948000
        },
        {
            "id": 13987,
            "name": "GetAddress",
            "className": "",
            "description": "获取Address信息",
            "path": "/api/get/address",
            "method": 1,
            "isRest": 1,
            "inputs": [
                {
                    "id": 27841,
                    "name": "userName",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户名信息",
                    "createTime": 1448958365000,
                    "updateTime": 1448958365000,
                    "defaultValue": ""
                },
                {
                    "id": 28631,
                    "name": "id",
                    "type": 10002,
                    "isPrimite": 0,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户id",
                    "createTime": 1449803381000,
                    "updateTime": 1449803381000,
                    "defaultValue": "100"
                },
                {
                    "id": 28632,
                    "name": "isLogin",
                    "type": 10003,
                    "isPrimite": 0,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户登录状态",
                    "createTime": 1449803406000,
                    "updateTime": 1449804212000,
                    "defaultValue": "false"
                },
                {
                    "id": 28633,
                    "name": "address",
                    "type": 11256,
                    "isPrimite": 0,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "用户地址",
                    "createTime": 1449803425000,
                    "updateTime": 1449803425000,
                    "defaultValue": ""
                },
                {
                    "id": 28634,
                    "name": "articles",
                    "type": 11302,
                    "isPrimite": 0,
                    "typeName": "Article",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "用户文章",
                    "createTime": 1449803449000,
                    "updateTime": 1449803449000,
                    "defaultValue": ""
                },
                {
                    "id": 28635,
                    "name": "commentIds",
                    "type": 10002,
                    "isPrimite": 0,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 1,
                    "description": "用户评论id",
                    "createTime": 1449803484000,
                    "updateTime": 1449803484000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 27842,
                    "name": "address",
                    "type": 11256,
                    "isPrimite": 0,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "具体地址字符串",
                    "createTime": 1448958365000,
                    "updateTime": 1449457766000,
                    "defaultValue": ""
                }
            ],
            "headers": [
                {
                    "id": 28628,
                    "name": "Content-Type",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "set content-type",
                    "createTime": 1449803313000,
                    "updateTime": 1449803313000,
                    "defaultValue": "application/text"
                },
                {
                    "id": 28629,
                    "name": "Cookie",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "set cookie",
                    "createTime": 1449803352000,
                    "updateTime": 1449803352000,
                    "defaultValue": "100"
                },
                {
                    "id": 28630,
                    "name": "Test",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449803363000,
                    "updateTime": 1449803363000,
                    "defaultValue": ""
                },
                {
                    "id": 28996,
                    "name": "AAA",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1450347800000,
                    "updateTime": 1450347800000,
                    "defaultValue": ""
                }
            ],
            "updateTime": 1450347800000
        },
        {
            "id": 14097,
            "name": "GetArticles",
            "className": "",
            "description": "",
            "path": "/articles",
            "method": 1,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28353,
                    "name": "articles",
                    "type": 11302,
                    "isPrimite": 0,
                    "typeName": "Article",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "createTime": 1449457994000,
                    "updateTime": 1449457994000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449457994000
        },
        {
            "id": 14098,
            "name": "GetArticlesWithAuthor",
            "className": "",
            "description": "",
            "path": "/articles",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28354,
                    "name": "author",
                    "type": 11300,
                    "isPrimite": 0,
                    "typeName": "Author",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449458058000,
                    "updateTime": 1449458058000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 28355,
                    "name": "articles",
                    "type": 11302,
                    "isPrimite": 0,
                    "typeName": "Article",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449458058000,
                    "updateTime": 1449458058000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449458058000
        },
        {
            "id": 14109,
            "name": "GetAuthorInfoCase5",
            "className": "",
            "description": "",
            "path": "/author/get/case5",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28368,
                    "name": "name",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459473000,
                    "updateTime": 1449459473000,
                    "defaultValue": ""
                },
                {
                    "id": 28369,
                    "name": "email",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459473000,
                    "updateTime": 1449459473000,
                    "defaultValue": ""
                },
                {
                    "id": 28370,
                    "name": "address",
                    "type": 11256,
                    "isPrimite": 0,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459473000,
                    "updateTime": 1449459473000,
                    "defaultValue": ""
                },
                {
                    "id": 28371,
                    "name": "subscribers",
                    "type": 11303,
                    "isPrimite": 0,
                    "typeName": "Subscriber",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "createTime": 1449459473000,
                    "updateTime": 1449459473000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449459473000
        },
        {
            "id": 14564,
            "name": "认真",
            "className": "Authorize",
            "description": "",
            "path": "/authorize",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 18678,
                    "datatypeId": 11602,
                    "datatypeName": "ResultData",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360849000,
                    "updateTime": 1453360849000,
                    "defaultValue": ""
                },
                {
                    "id": 18679,
                    "datatypeId": 11602,
                    "datatypeName": "ResultData",
                    "projectId": 11029,
                    "name": "errorMsg",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360849000,
                    "updateTime": 1453360849000,
                    "defaultValue": ""
                },
                {
                    "id": 18680,
                    "datatypeId": 11602,
                    "datatypeName": "ResultData",
                    "projectId": 11029,
                    "name": "data",
                    "originalType": 10000,
                    "type": 11256,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360849000,
                    "updateTime": 1453360857000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1453360857000
        },
        {
            "id": 14132,
            "name": "GetCategoryCase4",
            "className": "",
            "description": "",
            "path": "/category/get/case4",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28445,
                    "name": "code",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449545783000,
                    "updateTime": 1449545783000,
                    "defaultValue": ""
                },
                {
                    "id": 28446,
                    "name": "message",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449545783000,
                    "updateTime": 1449545783000,
                    "defaultValue": ""
                },
                {
                    "id": 28447,
                    "name": "result",
                    "type": 11313,
                    "isPrimite": 0,
                    "typeName": "Category",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449545783000,
                    "updateTime": 1449545783000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449545783000
        },
        {
            "id": 14123,
            "name": "GetComments",
            "className": "",
            "description": "",
            "path": "/comments/get",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 28403,
                    "name": "result",
                    "type": 11301,
                    "isPrimite": 0,
                    "typeName": "Comment",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "评论列表",
                    "createTime": 1449481301000,
                    "updateTime": 1449481315000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449481315000
        },
        {
            "id": 14216,
            "name": "ComplexHeader",
            "className": "",
            "description": "",
            "path": "/complex/header",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [],
            "headers": [
                {
                    "id": 17007,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "province",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "省",
                    "createTime": 1450091513000,
                    "updateTime": 1450091513000,
                    "defaultValue": "浙江"
                },
                {
                    "id": 17008,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "city",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "市",
                    "createTime": 1450091513000,
                    "updateTime": 1450091513000,
                    "defaultValue": "杭州"
                },
                {
                    "id": 17996,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "isChinese",
                    "originalType": 10003,
                    "type": 10003,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "是否中国人",
                    "createTime": 1450091513000,
                    "updateTime": 1450091513000,
                    "defaultValue": "true"
                }
            ],
            "updateTime": 1450091513000
        },
        {
            "id": 14357,
            "name": "添加请求",
            "className": "lwangTestRequest",
            "description": "",
            "path": "/post/lwang/test",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 29470,
                    "name": "name",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1451552779000,
                    "updateTime": 1451552779000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 29471,
                    "name": "title",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1451552779000,
                    "updateTime": 1451552779000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1451552779000
        },
        {
            "id": 14565,
            "name": "另一个认证",
            "className": "Renzhen",
            "description": "11111",
            "path": "/renzhen",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 18678,
                    "datatypeId": 11602,
                    "datatypeName": "ResultData",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360905000,
                    "updateTime": 1453360905000,
                    "defaultValue": ""
                },
                {
                    "id": 18679,
                    "datatypeId": 11602,
                    "datatypeName": "ResultData",
                    "projectId": 11029,
                    "name": "errorMsg",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360905000,
                    "updateTime": 1453360905000,
                    "defaultValue": ""
                },
                {
                    "id": 18680,
                    "datatypeId": 11602,
                    "datatypeName": "ResultData",
                    "projectId": 11029,
                    "name": "data",
                    "originalType": 10000,
                    "type": 11256,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "createTime": 1453360905000,
                    "updateTime": 1453360905000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1453360905000
        },
        {
            "id": 14567,
            "name": "Renzhen3",
            "className": "Renzhen3",
            "description": "",
            "path": "/renzhenNo",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 17213,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453361070000,
                    "updateTime": 1453361070000,
                    "defaultValue": ""
                },
                {
                    "id": 17214,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "message",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453361070000,
                    "updateTime": 1453361070000,
                    "defaultValue": ""
                },
                {
                    "id": 17215,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "testResult",
                    "originalType": 10000,
                    "type": 10003,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453361070000,
                    "updateTime": 1453361070000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1453361070000
        },
        {
            "id": 14566,
            "name": "认证2",
            "className": "Renzhen2",
            "description": "",
            "path": "/renzhenYes",
            "method": 0,
            "isRest": 1,
            "inputs": [],
            "outputs": [
                {
                    "id": 17213,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360960000,
                    "updateTime": 1453360960000,
                    "defaultValue": ""
                },
                {
                    "id": 17214,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "message",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360960000,
                    "updateTime": 1453360960000,
                    "defaultValue": ""
                },
                {
                    "id": 17215,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "testResult",
                    "originalType": 10000,
                    "type": 11302,
                    "typeName": "Article",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1453360960000,
                    "updateTime": 1453360960000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1453360960000
        },
        {
            "id": 14110,
            "name": "GetSubscribers",
            "className": "",
            "description": "",
            "path": "/subscriber/get/list",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28372,
                    "name": "author",
                    "type": 11300,
                    "isPrimite": 0,
                    "typeName": "Author",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459585000,
                    "updateTime": 1449459585000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 17213,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459585000,
                    "updateTime": 1449459585000,
                    "defaultValue": ""
                },
                {
                    "id": 17214,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "message",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449459585000,
                    "updateTime": 1449459585000,
                    "defaultValue": ""
                },
                {
                    "id": 17215,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "testResult",
                    "originalType": 10000,
                    "type": 11303,
                    "typeName": "Subscriber",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "createTime": 1449459585000,
                    "updateTime": 1449459585000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1449459585000
        },
        {
            "id": 14215,
            "name": "TestRequestHeader",
            "className": "",
            "description": "",
            "path": "/test/request/header",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28776,
                    "name": "user",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1450091269000,
                    "updateTime": 1450091269000,
                    "defaultValue": ""
                },
                {
                    "id": 28777,
                    "name": "password",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1450091269000,
                    "updateTime": 1450091269000,
                    "defaultValue": ""
                }
            ],
            "outputs": [],
            "headers": [
                {
                    "id": 28778,
                    "name": "Content-Type",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1450091269000,
                    "updateTime": 1450091307000,
                    "defaultValue": "application/json"
                },
                {
                    "id": 28779,
                    "name": "Cookie",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1450091269000,
                    "updateTime": 1450091269000,
                    "defaultValue": ""
                },
                {
                    "id": 28780,
                    "name": "UserInfo",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1450091269000,
                    "updateTime": 1450091269000,
                    "defaultValue": ""
                }
            ],
            "updateTime": 1450091308000
        },
        {
            "id": 14183,
            "name": "GetAddressPost",
            "className": "BBBB",
            "description": "获取Address信息",
            "path": "api/get/address",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28638,
                    "name": "userName",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户名信息",
                    "createTime": 1449806044000,
                    "updateTime": 1449806044000,
                    "defaultValue": ""
                },
                {
                    "id": 28639,
                    "name": "id",
                    "type": 10002,
                    "isPrimite": 0,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户id",
                    "createTime": 1449806044000,
                    "updateTime": 1449806044000,
                    "defaultValue": "100"
                },
                {
                    "id": 28640,
                    "name": "isLogin",
                    "type": 10003,
                    "isPrimite": 0,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户登录状态",
                    "createTime": 1449806044000,
                    "updateTime": 1449806044000,
                    "defaultValue": "false"
                },
                {
                    "id": 28641,
                    "name": "address",
                    "type": 11256,
                    "isPrimite": 0,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "用户地址",
                    "createTime": 1449806044000,
                    "updateTime": 1449806044000,
                    "defaultValue": ""
                },
                {
                    "id": 28642,
                    "name": "articles",
                    "type": 11302,
                    "isPrimite": 0,
                    "typeName": "Article",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "用户文章",
                    "createTime": 1449806044000,
                    "updateTime": 1449806044000,
                    "defaultValue": ""
                },
                {
                    "id": 28643,
                    "name": "commentIds",
                    "type": 10002,
                    "isPrimite": 0,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 1,
                    "description": "用户评论id",
                    "createTime": 1449806044000,
                    "updateTime": 1449806044000,
                    "defaultValue": ""
                },
                {
                    "id": 28723,
                    "name": "enumTest",
                    "type": 11315,
                    "isPrimite": 0,
                    "typeName": "EnumsTest",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "enums test",
                    "createTime": 1450063651000,
                    "updateTime": 1451373498000,
                    "defaultValue": ""
                },
                {
                    "id": 28946,
                    "name": "address2",
                    "type": 11256,
                    "isPrimite": 0,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "address 2",
                    "createTime": 1450266335000,
                    "updateTime": 1450266335000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 28671,
                    "name": "aaaaa",
                    "type": 11300,
                    "isPrimite": 0,
                    "typeName": "Author",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "createTime": 1449825268000,
                    "updateTime": 1449825792000,
                    "defaultValue": ""
                }
            ],
            "headers": [],
            "updateTime": 1451373498000
        },
        {
            "id": 14189,
            "name": "GetAddressPost2",
            "className": "",
            "description": "获取Address信息",
            "path": "http://127.0.0.1/api/get/address2",
            "method": 0,
            "isRest": 1,
            "inputs": [
                {
                    "id": 17007,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "province",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "省",
                    "createTime": 1449826081000,
                    "updateTime": 1449826081000,
                    "defaultValue": "浙江"
                },
                {
                    "id": 17008,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "city",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "市",
                    "createTime": 1449826081000,
                    "updateTime": 1449826081000,
                    "defaultValue": "杭州"
                },
                {
                    "id": 17996,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "isChinese",
                    "originalType": 10003,
                    "type": 10003,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "是否中国人",
                    "createTime": 1449826081000,
                    "updateTime": 1449826081000,
                    "defaultValue": "true"
                }
            ],
            "outputs": [
                {
                    "id": 28672,
                    "name": "aaaaa",
                    "type": 11300,
                    "isPrimite": 0,
                    "typeName": "Author",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "createTime": 1449826074000,
                    "updateTime": 1449826074000,
                    "defaultValue": ""
                },
                {
                    "id": 28678,
                    "name": "bbbbb",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449826901000,
                    "updateTime": 1449826901000,
                    "defaultValue": ""
                }
            ],
            "headers": [
                {
                    "id": 28673,
                    "name": "Content-Type",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "set content-type",
                    "createTime": 1449826074000,
                    "updateTime": 1449826074000,
                    "defaultValue": "application/text"
                },
                {
                    "id": 28674,
                    "name": "Cookie",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "set cookie",
                    "createTime": 1449826074000,
                    "updateTime": 1449826074000,
                    "defaultValue": "100"
                },
                {
                    "id": 28675,
                    "name": "Test",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449826074000,
                    "updateTime": 1449826074000,
                    "defaultValue": ""
                }
            ],
            "updateTime": 1449826902000
        },
        {
            "id": 14188,
            "name": "GetAddressPut",
            "className": "",
            "description": "获取Address信息",
            "path": "http://127.0.0.1/api/uploadFile",
            "method": 2,
            "isRest": 1,
            "inputs": [
                {
                    "id": 28662,
                    "name": "userName",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户名信息",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": ""
                },
                {
                    "id": 28663,
                    "name": "id",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户id",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": "100"
                },
                {
                    "id": 28664,
                    "name": "isLogin",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户登录状态",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": "false"
                },
                {
                    "id": 28665,
                    "name": "address",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户地址",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": ""
                },
                {
                    "id": 28666,
                    "name": "articles",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "article",
                    "createTime": 1449824775000,
                    "updateTime": 1450179013000,
                    "defaultValue": ""
                },
                {
                    "id": 28667,
                    "name": "commentIds",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "用户评论id",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": ""
                }
            ],
            "outputs": [
                {
                    "id": 17213,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "code",
                    "originalType": 10002,
                    "type": 10002,
                    "typeName": "Number",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1451386668000,
                    "updateTime": 1451386668000,
                    "defaultValue": ""
                },
                {
                    "id": 17214,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "message",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1451386668000,
                    "updateTime": 1451386668000,
                    "defaultValue": ""
                },
                {
                    "id": 17215,
                    "datatypeId": 11307,
                    "datatypeName": "ResultDatadddt",
                    "projectId": 11029,
                    "name": "testResult",
                    "originalType": 10000,
                    "type": 11256,
                    "typeName": "Address",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1451386668000,
                    "updateTime": 1451457574000,
                    "defaultValue": ""
                }
            ],
            "headers": [
                {
                    "id": 28668,
                    "name": "Content-Type",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "set content-type",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": "application/text"
                },
                {
                    "id": 28669,
                    "name": "Cookie",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "set cookie",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": "100"
                },
                {
                    "id": 28670,
                    "name": "Test",
                    "type": 10001,
                    "isPrimite": 0,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "createTime": 1449824775000,
                    "updateTime": 1449824775000,
                    "defaultValue": ""
                }
            ],
            "updateTime": 1451457882000
        }
    ],
    "templates": [
        {
            "id": 10844,
            "path": "/page/index.ftl",
            "name": "首页",
            "description": "",
            "parameters": [
                {
                    "id": 17007,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "province",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "省",
                    "updateTime": 1454307459000,
                    "defaultValue": "浙江"
                },
                {
                    "id": 17008,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "city",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "市",
                    "updateTime": 1454307459000,
                    "defaultValue": "杭州"
                },
                {
                    "id": 17996,
                    "datatypeId": 11256,
                    "datatypeName": "Address",
                    "projectId": 11029,
                    "name": "isChinese",
                    "originalType": 10003,
                    "type": 10003,
                    "typeName": "Boolean",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "是否中国人",
                    "updateTime": 1454307459000,
                    "defaultValue": "true"
                },
                {
                    "id": 17190,
                    "datatypeId": 11302,
                    "datatypeName": "Article",
                    "projectId": 11029,
                    "name": "title",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "updateTime": 1454307463000,
                    "defaultValue": ""
                },
                {
                    "id": 17191,
                    "datatypeId": 11302,
                    "datatypeName": "Article",
                    "projectId": 11029,
                    "name": "body",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "updateTime": 1454307463000,
                    "defaultValue": ""
                },
                {
                    "id": 17192,
                    "datatypeId": 11302,
                    "datatypeName": "Article",
                    "projectId": 11029,
                    "name": "authorAAA",
                    "originalType": 11300,
                    "type": 11300,
                    "typeName": "Author",
                    "isSysType": 0,
                    "isArray": 0,
                    "description": "",
                    "updateTime": 1454307463000,
                    "defaultValue": ""
                },
                {
                    "id": 17193,
                    "datatypeId": 11302,
                    "datatypeName": "Article",
                    "projectId": 11029,
                    "name": "comments",
                    "originalType": 11301,
                    "type": 11301,
                    "typeName": "Comment",
                    "isSysType": 0,
                    "isArray": 1,
                    "description": "",
                    "updateTime": 1454307463000,
                    "defaultValue": ""
                },
                {
                    "id": 18058,
                    "datatypeId": 11302,
                    "datatypeName": "Article",
                    "projectId": 11029,
                    "name": "test",
                    "originalType": 10001,
                    "type": 10001,
                    "typeName": "String",
                    "isSysType": 1,
                    "isArray": 0,
                    "description": "",
                    "updateTime": 1454307463000,
                    "defaultValue": ""
                }
            ],
            "updateTime": 1454307463000
        }
    ],
    "datatypes": [
        {
            "id": 10003,
            "name": "Boolean",
            "format": 0,
            "subtype": 0,
            "updateTime": 1438339452000,
            "description": "布尔"
        },
        {
            "id": 10002,
            "name": "Number",
            "format": 0,
            "subtype": 0,
            "updateTime": 1438339452000,
            "description": "数值"
        },
        {
            "id": 10001,
            "name": "String",
            "format": 0,
            "subtype": 0,
            "updateTime": 1438339452000,
            "description": "字符串"
        },
        {
            "id": 10000,
            "name": "Variable",
            "format": 0,
            "subtype": 0,
            "updateTime": 1438339452000,
            "description": "可变类型"
        },
        {
            "id": 11256,
            "name": "Address",
            "format": 0,
            "subtype": 0,
            "updateTime": 1451455001000,
            "description": "地址信息"
        },
        {
            "id": 11302,
            "name": "Article",
            "format": 0,
            "subtype": 0,
            "updateTime": 1451464449000,
            "description": "文章"
        },
        {
            "id": 11300,
            "name": "Author",
            "format": 0,
            "subtype": 0,
            "updateTime": 1450255813000,
            "description": ""
        },
        {
            "id": 11512,
            "name": "Bai",
            "format": 0,
            "subtype": 0,
            "updateTime": 1452505181000,
            "description": ""
        },
        {
            "id": 11313,
            "name": "Category",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449545730000,
            "description": "测试Category接口"
        },
        {
            "id": 11301,
            "name": "Comment",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457527000,
            "description": "注释"
        },
        {
            "id": 11315,
            "name": "EnumsTest",
            "format": 1,
            "subtype": 0,
            "updateTime": 1450337872000,
            "description": ""
        },
        {
            "id": 11389,
            "name": "EnumsTest2",
            "format": 1,
            "subtype": 0,
            "updateTime": 1450345142000,
            "description": ""
        },
        {
            "id": 11454,
            "name": "HahaTest",
            "format": 0,
            "subtype": 0,
            "updateTime": 1451375148000,
            "description": ""
        },
        {
            "id": 11357,
            "name": "HelloArrTest",
            "format": 0,
            "subtype": 0,
            "updateTime": 1450085355000,
            "description": ""
        },
        {
            "id": 11299,
            "name": "ItemDetail",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457428000,
            "description": ""
        },
        {
            "id": 11304,
            "name": "Person",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457685000,
            "description": ""
        },
        {
            "id": 11293,
            "name": "ProductInfo",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457063000,
            "description": "产品信息"
        },
        {
            "id": 11294,
            "name": "ProductResponse",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457133000,
            "description": "自定义类型"
        },
        {
            "id": 11602,
            "name": "ResultData",
            "format": 0,
            "subtype": 0,
            "updateTime": 1453360827000,
            "description": "ResultData"
        },
        {
            "id": 11307,
            "name": "ResultDatadddt",
            "format": 0,
            "subtype": 0,
            "updateTime": 1454295473000,
            "description": ""
        },
        {
            "id": 11297,
            "name": "SkuSpecInfo",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457300000,
            "description": ""
        },
        {
            "id": 11295,
            "name": "Spec",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457173000,
            "description": "Spec信息"
        },
        {
            "id": 11303,
            "name": "Subscriber",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457628000,
            "description": "订阅者"
        },
        {
            "id": 11306,
            "name": "TestShipAddress",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449458379000,
            "description": ""
        },
        {
            "id": 11296,
            "name": "TestSkuInfo",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457233000,
            "description": ""
        },
        {
            "id": 11298,
            "name": "TestSkuSpec",
            "format": 0,
            "subtype": 0,
            "updateTime": 1449457366000,
            "description": ""
        },
        {
            "id": 11509,
            "name": "TestStatusCode",
            "format": 1,
            "subtype": 0,
            "updateTime": 1452496246000,
            "description": "枚举类型"
        },
        {
            "id": 11305,
            "name": "UserInfo",
            "format": 0,
            "subtype": 0,
            "updateTime": 1451294549000,
            "description": "用户信息"
        }
    ],
    "attributes": [
        {
            "id": 17007,
            "name": "province",
            "type": 10001,
            "isArray": 0,
            "description": "省",
            "parentId": 11256,
            "vkey": "",
            "defaultValue": "浙江"
        },
        {
            "id": 17008,
            "name": "city",
            "type": 10001,
            "isArray": 0,
            "description": "市",
            "parentId": 11256,
            "vkey": "",
            "defaultValue": "杭州"
        },
        {
            "id": 17996,
            "name": "isChinese",
            "type": 10003,
            "isArray": 0,
            "description": "是否中国人",
            "parentId": 11256,
            "vkey": "",
            "defaultValue": "true"
        },
        {
            "id": 17190,
            "name": "title",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11302,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17191,
            "name": "body",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11302,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17192,
            "name": "authorAAA",
            "type": 11300,
            "isArray": 0,
            "description": "",
            "parentId": 11302,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17193,
            "name": "comments",
            "type": 11301,
            "isArray": 1,
            "description": "",
            "parentId": 11302,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 18058,
            "name": "test",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11302,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17182,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11300,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17183,
            "name": "email",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11300,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17184,
            "name": "address",
            "type": 11256,
            "isArray": 0,
            "description": "",
            "parentId": 11300,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17539,
            "name": "isMine",
            "type": 10003,
            "isArray": 0,
            "description": "",
            "parentId": 11300,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17540,
            "name": "hasMore",
            "type": 10003,
            "isArray": 0,
            "description": "",
            "parentId": 11300,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 18200,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11512,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17244,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11313,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17245,
            "name": "title",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11313,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17185,
            "name": "skuInfo",
            "type": 10003,
            "isArray": 1,
            "description": "",
            "parentId": 11301,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17186,
            "name": "content",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11301,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17187,
            "name": "username",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11301,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17188,
            "name": "count",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11301,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17189,
            "name": "isShow",
            "type": 10003,
            "isArray": 0,
            "description": "",
            "parentId": 11301,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17256,
            "name": "1",
            "type": 10000,
            "isArray": 0,
            "description": "aa",
            "parentId": 11315,
            "vkey": "a",
            "defaultValue": ""
        },
        {
            "id": 17257,
            "name": "2",
            "type": 10000,
            "isArray": 0,
            "description": "bb",
            "parentId": 11315,
            "vkey": "b",
            "defaultValue": ""
        },
        {
            "id": 17258,
            "name": "3",
            "type": 10000,
            "isArray": 0,
            "description": "cc",
            "parentId": 11315,
            "vkey": "c",
            "defaultValue": ""
        },
        {
            "id": 17912,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11454,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17913,
            "name": "title",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11454,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17177,
            "name": "detailHtml",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11299,
            "vkey": "",
            "defaultValue": "fiXELadCKx"
        },
        {
            "id": 17178,
            "name": "picUrl1",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11299,
            "vkey": "",
            "defaultValue": "yeVwxLglSe"
        },
        {
            "id": 17179,
            "name": "picUrl2",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11299,
            "vkey": "",
            "defaultValue": "YpySwxGzwO"
        },
        {
            "id": 17180,
            "name": "picUrl3",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11299,
            "vkey": "",
            "defaultValue": "GyiiwwloqT"
        },
        {
            "id": 17181,
            "name": "picUrl4",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11299,
            "vkey": "",
            "defaultValue": "GcHNvTIXiw"
        },
        {
            "id": 17198,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11304,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17199,
            "name": "son",
            "type": 11304,
            "isArray": 0,
            "description": "",
            "parentId": 11304,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17591,
            "name": "1",
            "type": 10000,
            "isArray": 0,
            "description": "aa",
            "parentId": 11389,
            "vkey": "a",
            "defaultValue": ""
        },
        {
            "id": 17592,
            "name": "2",
            "type": 10000,
            "isArray": 0,
            "description": "bb",
            "parentId": 11389,
            "vkey": "b",
            "defaultValue": ""
        },
        {
            "id": 17593,
            "name": "3",
            "type": 10000,
            "isArray": 0,
            "description": "cc",
            "parentId": 11389,
            "vkey": "c",
            "defaultValue": ""
        },
        {
            "id": 17157,
            "name": "product",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11293,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17158,
            "name": "price",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11293,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17159,
            "name": "title",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11294,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17160,
            "name": "info",
            "type": 11293,
            "isArray": 0,
            "description": "",
            "parentId": 11294,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 18678,
            "name": "code",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11602,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 18679,
            "name": "errorMsg",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11602,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 18680,
            "name": "data",
            "type": 10000,
            "isArray": 0,
            "description": "",
            "parentId": 11602,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17213,
            "name": "code",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11307,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17214,
            "name": "message",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11307,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17215,
            "name": "testResult",
            "type": 10000,
            "isArray": 0,
            "description": "",
            "parentId": 11307,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17169,
            "name": "id",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11297,
            "vkey": "",
            "defaultValue": "58983"
        },
        {
            "id": 17170,
            "name": "skuSpecId",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11297,
            "vkey": "",
            "defaultValue": "35541"
        },
        {
            "id": 17171,
            "name": "picUrl",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11297,
            "vkey": "",
            "defaultValue": "iFrBzaenbM"
        },
        {
            "id": 17172,
            "name": "value",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11297,
            "vkey": "",
            "defaultValue": "dLWSRJKodf"
        },
        {
            "id": 17194,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11303,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17195,
            "name": "email",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11303,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17196,
            "name": "address",
            "type": 11256,
            "isArray": 0,
            "description": "",
            "parentId": 11303,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17197,
            "name": "author",
            "type": 11300,
            "isArray": 1,
            "description": "",
            "parentId": 11303,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17202,
            "name": "id",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "179"
        },
        {
            "id": 17203,
            "name": "provinceId",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "89231"
        },
        {
            "id": 17204,
            "name": "provinceName",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "tREoxqloFh"
        },
        {
            "id": 17205,
            "name": "cityId",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "1970"
        },
        {
            "id": 17206,
            "name": "cityName",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "iOEMsOWnFy"
        },
        {
            "id": 17207,
            "name": "districtId",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "21323"
        },
        {
            "id": 17208,
            "name": "districtName",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "HdzcXYClHT"
        },
        {
            "id": 17209,
            "name": "address",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "jKYzoEZOdF"
        },
        {
            "id": 17210,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "dDiDmsUeMU"
        },
        {
            "id": 17211,
            "name": "mobile",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "JDDGVcpNOE"
        },
        {
            "id": 17212,
            "name": "dft",
            "type": 10003,
            "isArray": 0,
            "description": "",
            "parentId": 11306,
            "vkey": "",
            "defaultValue": "1"
        },
        {
            "id": 17163,
            "name": "id",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11296,
            "vkey": "",
            "defaultValue": "62267"
        },
        {
            "id": 17164,
            "name": "counterPrice",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11296,
            "vkey": "",
            "defaultValue": "77427"
        },
        {
            "id": 17165,
            "name": "retailPrice",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11296,
            "vkey": "",
            "defaultValue": "80649"
        },
        {
            "id": 17166,
            "name": "primarySku",
            "type": 10003,
            "isArray": 0,
            "description": "",
            "parentId": 11296,
            "vkey": "",
            "defaultValue": "0"
        },
        {
            "id": 17167,
            "name": "sellVolume",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11296,
            "vkey": "",
            "defaultValue": "47879"
        },
        {
            "id": 17168,
            "name": "valid",
            "type": 10003,
            "isArray": 0,
            "description": "",
            "parentId": 11296,
            "vkey": "",
            "defaultValue": "0"
        },
        {
            "id": 17173,
            "name": "id",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11298,
            "vkey": "",
            "defaultValue": "87425"
        },
        {
            "id": 17174,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11298,
            "vkey": "",
            "defaultValue": "BHoKhaQoCg"
        },
        {
            "id": 17175,
            "name": "type",
            "type": 10002,
            "isArray": 0,
            "description": "",
            "parentId": 11298,
            "vkey": "",
            "defaultValue": "49849"
        },
        {
            "id": 17176,
            "name": "skuSpecValueList",
            "type": 11297,
            "isArray": 1,
            "description": "",
            "parentId": 11298,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17481,
            "name": "ids",
            "type": 10002,
            "isArray": 1,
            "description": "",
            "parentId": 11357,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 18191,
            "name": "200",
            "type": 10000,
            "isArray": 0,
            "description": "",
            "parentId": 11509,
            "vkey": "key1",
            "defaultValue": ""
        },
        {
            "id": 18192,
            "name": "500",
            "type": 10000,
            "isArray": 0,
            "description": "",
            "parentId": 11509,
            "vkey": "key2",
            "defaultValue": ""
        },
        {
            "id": 17200,
            "name": "name",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11305,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17201,
            "name": "token",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11305,
            "vkey": "",
            "defaultValue": ""
        },
        {
            "id": 17161,
            "name": "specName",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11295,
            "vkey": "",
            "defaultValue": "YfDClGDtNz"
        },
        {
            "id": 17162,
            "name": "specValue",
            "type": 10001,
            "isArray": 0,
            "description": "",
            "parentId": 11295,
            "vkey": "",
            "defaultValue": "uEEkOmPptb"
        }
    ],
    "project": {
        "id": 11029,
        "name": "HearTouch",
        "group": "HT代码自动生成"
    },
    "timestamp": 1454307520833
};